#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: Software@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
